[workspace]
members = [
    "binary_search",
    "factorization",
    "fenwick_tree",
    "grid",
    "next_permutation",
    "procon_reader",
    "rolling_hash",
    "system_test_tool",
    "union_find",
    "util_macro",
    "z_algorithm"
]
