[workspace]
members = [
    "binary-search",
    "factorization",
    "fenwick-tree",
    "grid",
    "next-permutation",
    "procon-reader",
    "rolling-hash",
    "union-find",
    "util-macro",
    "z-algorithm"
]
